lavatar:
  # build: .
  image: rroemhild/lavatar
  links:
    - redis
    - openldap
  ports:
    - 5000:5000
  environment:
    - DEBUG=True
    - USE_REDIS=True
    - LDAP_SERVER=openldap
    - LDAP_BINDDN=cn=admin,dc=planetexpress,dc=com
    - LDAP_SECRET=GoodNewsEveryone
    - LDAP_USER_BASEDN=ou=people,dc=planetexpress,dc=com
redis:
  image: redis
openldap:
  image: rroemhild/test-openldap
